apiVersion: validation.spectrocloud.labs/v1alpha1
kind: OciValidator
metadata:
  name: ocivalidator-sample-oci-registry
spec:
  ociRegistryRules:
    # public oci registry artifact with tag
    - host: "registry-1.docker.io"
      artifacts:
        - ref: "bitnamicharts/mysql:9.14.3"

    # public oci registry artifact referenced by default "latest" tag
    - host: "registry.hub.docker.com"
      artifacts:
        - ref: "ahmadibraspectrocloud/kubebuilder-cron"
          download: true

    # public ecr registry artifact referenced by default "latest" tag
    - host: "public.ecr.aws"
      artifacts:
        - ref: "u5n5j0b4/oci-test-public"
          download: true
