apiVersion: validation.spectrocloud.labs/v1alpha1
kind: OciValidator
metadata:
  name: ocivalidator-sample-public-oci-registries
spec:
  ociRegistryRules:
    # public oci registry artifact with tag
    - host: "docker.io"
      artifacts:
        - ref: "library/redis:7.2.4"
          layerValidation: true

    # public oci registry artifact referenced by default "latest" tag
    - host: "registry.hub.docker.com"
      artifacts:
        - ref: "ahmadibraspectrocloud/kubebuilder-cron"
          layerValidation: true

    # public ecr registry artifact referenced by default "latest" tag
    - host: "public.ecr.aws"
      artifacts:
        - ref: "u5n5j0b4/oci-test-public"
          layerValidation: true
