
name: GoVulnCheck

on: [pull_request]

concurrency:
  group: govulncheck-${{ github.ref }}
  cancel-in-progress: true

jobs:
  govulncheck-pr-scan:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/spectro-images-public/golang:1.21-alpine
    steps:
      - name: install-govulncheck
        run: GOBIN=/usr/local/bin go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: govulncheck-scan
        run: |
          go version
          govulncheck -mode source ./...
