name: GoLicenses

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: golicenses-${{ github.ref }}
  cancel-in-progress: true

jobs:
  golicense-pr-scan:
    runs-on: ubuntu-latest
    steps:
      - name: install-git
        run: sudo apt-get install -y git

      - name: install-golicenses
        run: GOBIN=/usr/local/bin go install github.com/google/go-licenses@v1.0.0

      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
        with:
          go-version: '1.21'

      - name: golicense-scan
        run: |
          go-licenses check ./...
